import App from "./App";
import {createRoot} from 'react-dom/client';
import {MemoryRouter,BrowserRouter,Routes,Route,Link} from 'react-router-dom';
import '/src/index.css';
import Dashboard from './pages/AdminDashboard';
import Upload from './pages/TeacherUpload';
import Reports from './pages/ReportsPage';
import Messages from './pages/MessagesPage';
import Templates from './pages/MessageTemplatesPage';
import Import from './pages/ImportStudents';
import Seed from './pages/SeedPage';
import Settings from './pages/SettingsPage';
import Details from './pages/ClassDetails';
import Lates from './pages/LateStudentsPage';
import Owner from './pages/SuperAdminPage';
const pages={dashboard:Dashboard,upload:Upload,reports:Reports,messages:Messages,templates:Templates,import:Import,seed:Seed,settings:Settings,details:Details,lates:Lates,owner:Owner};
const key=new URLSearchParams(location.search).get('page')||'dashboard'; const Page=pages[key];
createRoot(document.getElementById('root')).render(<MemoryRouter>{key === "shell" ? <App /> : <div className="app-shell" dir="rtl"><main className="workspace max-w-7xl mx-auto py-6 px-3 sm:px-6 lg:px-8"><Page /></main></div>}</MemoryRouter>);
